# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian-x64"
  # config.vm.box_url = "http://www.googledrive.com/host/0BwjA0DjH-XVzMkJNX2k5aU5kNGM"
  config.vm.box_url = "/Users/w8ing4what/Google Drive/VagrantBox/debian-607-x64-vbox4210.box"
  config.vm.synced_folder "../.", "/home/vagrant/code" 
  # config.ssh.forward_x11 = true
  # config.vm.network "forwarded_port", guest: 8000, host: 8000, auto_correct: true
  # config.vm.network "forwarded_port", guest: 3000, host: 3000, auto_correct: true
  # config.vm.network "forwarded_port", guest: 5432, host: 5432, auto_correct: true
  # config.vm.network "private_network", ip: "192.168.10.10"
  # config.vm.provider :virtualbox do |virtualbox|
  #  virtualbox.customize ["modifyvm", :id, "--name", "vagrant"] # Name the INSTANCE (app), make unique
  #  virtualbox.customize ["modifyvm", :id, "--memory", "2048"]
  # end
  config.vm.provision :puppet do |puppet|
    puppet.module_path      = "modules"
    puppet.manifests_path  = "manifests"
    puppet.manifest_file      = "init.pp"
  end
end

